Traceback (most recent call last):
  File "/home/wxt/huatong/TRL_FT/test_code/PRO/eval_hh/infer_and_eval_main_reward.py", line 16, in <module>
    from infer_func_now import setup_seed, generate_pipeline, ranking_pipeline
ImportError: cannot import name 'ranking_pipeline' from 'infer_func_now' (/home/wxt/huatong/TRL_FT/test_code/PRO/eval_hh/infer_func_now.py)
Traceback (most recent call last):
  File "/home/wxt/huatong/TRL_FT/test_code/PRO/eval_hh/infer_and_eval_main_reward.py", line 16, in <module>
    from infer_func_now import setup_seed, generate_pipeline, ranking_pipeline
ImportError: cannot import name 'ranking_pipeline' from 'infer_func_now' (/home/wxt/huatong/TRL_FT/test_code/PRO/eval_hh/infer_func_now.py)
Traceback (most recent call last):
  File "/home/wxt/huatong/TRL_FT/test_code/PRO/eval_hh/infer_and_eval_main_reward.py", line 16, in <module>
    from infer_func_now import setup_seed, generate_pipeline, ranking_pipeline
ImportError: cannot import name 'ranking_pipeline' from 'infer_func_now' (/home/wxt/huatong/TRL_FT/test_code/PRO/eval_hh/infer_func_now.py)
Traceback (most recent call last):
  File "/home/wxt/huatong/TRL_FT/test_code/PRO/eval_hh/infer_and_eval_main_reward.py", line 16, in <module>
    from infer_func_now import setup_seed, generate_pipeline, ranking_pipeline
ImportError: cannot import name 'ranking_pipeline' from 'infer_func_now' (/home/wxt/huatong/TRL_FT/test_code/PRO/eval_hh/infer_func_now.py)
[2024-05-11 14:27:21,865] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3718378) of binary: /home/wxt/.conda/envs/halos3/bin/python
Traceback (most recent call last):
  File "/home/wxt/.conda/envs/halos3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/wxt/.conda/envs/halos3/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/wxt/.conda/envs/halos3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 970, in launch_command
    multi_gpu_launcher(args)
  File "/home/wxt/.conda/envs/halos3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/wxt/.conda/envs/halos3/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/wxt/.conda/envs/halos3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wxt/.conda/envs/halos3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
infer_and_eval_main_reward.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-11_14:27:21
  host      : design-agent-09.internal.cloudapp.net
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3718379)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-05-11_14:27:21
  host      : design-agent-09.internal.cloudapp.net
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3718380)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-05-11_14:27:21
  host      : design-agent-09.internal.cloudapp.net
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 3718381)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-11_14:27:21
  host      : design-agent-09.internal.cloudapp.net
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3718378)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
